feat: add pr close and fix some refs in the workflow

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,7 +4,7 @@ description: 'Deploy a Crunchy PostgreSQL database to OpenShift'
 inputs:
   directory:
     description: 'Crunchy Chart directory'
-    default: 'actions/crunchy/charts/crunchy'
+    default: 'charts/crunchy'
     required: false
   oc_server:
     description: 'OpenShift server'
@@ -90,8 +90,11 @@ runs:
         RELEASE_NAME=pg-$(echo -n "${{github.event.repository.name}}" | md5sum | cut -c 1-8)
         echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_OUTPUT
         echo "Release name: ${RELEASE_NAME}"
+        echo "CLUSTER_NAME=${RELEASE_NAME}-crunchy" >> $GITHUB_OUTPUT
+        echo "Cluster name:${RELEASE_NAME}-crunchy"
     - name: Deploy Database
       uses: bcgov/action-oc-runner@v1.2.0
+      if: (github.event.action == 'closed') # avoid running on PR close event, which unnecessarily patches the cluster.
       with:
         oc_namespace: ${{ inputs.oc_namespace }}
         oc_token: ${{ inputs.oc_token }}
@@ -151,7 +154,7 @@ runs:
         commands: |
           echo 'Adding PR specific user to Crunchy DB'
           NEW_USER='{"databases":["app-${{ github.event.number }}"],"name":"app-${{ github.event.number }}"}'
-          CURRENT_USERS=$(oc get PostgresCluster/${{steps.release_name.outputs.RELEASE_NAME}}-crunchy -o json | jq '.spec.users')
+          CURRENT_USERS=$(oc get PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} -o json | jq '.spec.users')
           echo "${CURRENT_USERS}"
 
           # check if current_users already contains the new_user
@@ -162,11 +165,11 @@ runs:
 
           UPDATED_USERS=$(echo "${CURRENT_USERS}" | jq --argjson NEW_USER "${NEW_USER}" '. + [$NEW_USER]')
           PATCH_JSON=$(jq -n --argjson users "${UPDATED_USERS}" '{"spec": {"users": $users}}')
-          oc patch PostgresCluster/${{steps.release_name.outputs.RELEASE_NAME}}-crunchy --type=merge -p "${PATCH_JSON}"
+          oc patch PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} --type=merge -p "${PATCH_JSON}"
           # wait for sometime as it takes time to create the user, query the secret and check if it is created, otherwise wait in a loop for 5 rounds
           SECRET_FOUND=false
           for i in {1..5}; do
-            if oc get secret ${{steps.release_name.outputs.RELEASE_NAME}}-crunchy-pguser-app-${{ github.event.number }} -o jsonpath='{.metadata.name}' > /dev/null 2>&1; then
+            if oc get secret ${{steps.release_name.outputs.CLUSTER_NAME}}-pguser-app-${{ github.event.number }} -o jsonpath='{.metadata.name}' > /dev/null 2>&1; then
               echo "Secret created"
               SECRET_FOUND=true
               break
@@ -177,6 +180,36 @@ runs:
           done
 
           if [ "$SECRET_FOUND" = false ]; then
-            echo "Error: Secret ${{steps.release_name.outputs.RELEASE_NAME}}-crunchy-pguser-app-${{ github.event.number }} was not created after 5 attempts."
+            echo "Error: Secret ${{steps.release_name.outputs.CLUSTER_NAME}}-pguser-app-${{ github.event.number }} was not created after 5 attempts."
             exit 1
           fi
+    - name: Remove PR specific user from Crunchy DB # only for PRs and when PR is closed
+      if: (github.event_name == 'pull_request' && github.event.action == 'closed')
+      uses: bcgov/action-oc-runner@v1.2.0
+      with:
+        oc_namespace: ${{ secrets.oc_namespace }}
+        oc_token: ${{ secrets.oc_token }}
+        oc_server: ${{ vars.oc_server }}
+        triggers: ${{ inputs.triggers }}
+        commands: |
+          # check if postgres-crunchy exists or else exit
+          oc get PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} || exit 0
+          # Remove the user from the crunchy cluster yaml and apply the changes
+          USER_TO_REMOVE='{"databases":["app-${{ github.event.number }}"],"name":"app-${{ github.event.number }}"}'
+          
+          echo 'getting current users from crunchy'
+          CURRENT_USERS=$(oc get PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} -o json | jq '.spec.users')
+          echo "${CURRENT_USERS}"
+          
+          # Remove the user from the list, 
+          UPDATED_USERS=$(echo "${CURRENT_USERS}" | jq --argjson user "${USER_TO_REMOVE}" 'map(select(. != $user))')
+          PATCH_JSON=$(jq -n --argjson users "${UPDATED_USERS}" '{"spec": {"users": $users}}')
+          oc patch PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} --type=merge -p "${PATCH_JSON}"
+          
+          # get primary crunchy pod and remove the role and db
+          CRUNCHY_PG_PRIMARY_POD_NAME=$(oc get pods -l postgres-operator.crunchydata.com/cluster=${{steps.release_name.outputs.CLUSTER_NAME}},postgres-operator.crunchydata.com/role=master -o json | jq -r '.items[0].metadata.name')
+          
+          echo "${CRUNCHY_PG_PRIMARY_POD_NAME}"
+          # Terminate all connections to the database before trying terminate and Drop the databse and role right after
+          oc exec -it "${CRUNCHY_PG_PRIMARY_POD_NAME}" -- bash -c "psql -U postgres -d postgres -c \"SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'app-${{ github.event.number }}' AND pid <> pg_backend_pid();\" && \psql -U postgres -d postgres -c \"DROP DATABASE \\\"app-${{ github.event.number }}\\\";\" && \psql -U postgres -d postgres -c \"DROP ROLE \\\"app-${{ github.event.number }}\\\";\""
+          echo 'database and role deleted'
