Cleanup and pare down

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -54,41 +54,30 @@ runs:
       run: |
         # Variables and Inputs
 
-        # S3 backup configuration
+        # Count S3 vars and respond accordingly
         s3_vars=("${{ inputs.s3_access_key }}" "${{ inputs.s3_secret_key }}" "${{ inputs.s3_bucket }}" "${{ inputs.s3_endpoint }}")
         s3_vars_count=0
-
         for var in "${s3_vars[@]}"; do
           [ -n "$var" ] && s3_vars_count=$((s3_vars_count+1))
         done
 
+        # Enable S3 backups if all required vars are set
         if [ "$s3_vars_count" -eq ${#s3_vars[@]} ]; then
           echo "All S3 configuration variables are present. Enabling S3 backups."
-          s3_enabled=true
+          S3_ENABLED=true
         elif [ "$s3_vars_count" -gt 0 ]; then
           echo "Warning: Some S3 configuration variables are set, but not all. Please ensure all S3 variables are configured."
-          s3_enabled=false
           exit 1
         else
           echo "S3 configuration not set. Disabling S3 backups."
-          s3_enabled=false
         fi
-        echo "s3_enabled=${s3_enabled}"
-        echo "s3_enabled=${s3_enabled}" >> $GITHUB_ENV
 
-        # Release Name
+        # Release Name; based on a hash of the repository name
         RELEASE_NAME=pg-$(echo -n "${{github.event.repository.name}}" | md5sum | cut -c 1-8)
-        echo "Release name: ${RELEASE_NAME}"
-        echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
-        echo "Cluster name: ${RELEASE_NAME}-crunchy"
-        echo "CLUSTER_NAME=${RELEASE_NAME}-crunchy" >> $GITHUB_ENV
 
-        # Construct values.yml URL
-        # ref_name = PR branch, ref_name = merge branch, default_branch = default branch
+        # Construct values.yml URL (ref_name = PR, ref_name = merge, default_branch = default)
         BRANCH_OR_REF="${{ github.head_ref || github.ref_name || github.event.repository.default_branch }}"
         VALUES_URL="https://raw.githubusercontent.com/${{ github.repository }}/${BRANCH_OR_REF}/${{ inputs.values_file }}"
-        echo "Constructed values.yml URL: ${VALUES_URL}"
-        echo "VALUES_URL=${VALUES_URL}" >> $GITHUB_ENV
 
         # Validate values.yml URL
         if ! curl --output /dev/null --silent --head --fail "${VALUES_URL}"; then
@@ -96,6 +85,19 @@ runs:
           exit 1
         fi
         echo "Validated values.yml URL: ${VALUES_URL}"
+
+        # Iterate through a list of variables and check their values
+        echo "Summary of variables:"
+        for var_name in "s3_enabled" "RELEASE_NAME" "CLUSTER_NAME" "VALUES_URL"; do
+          var_value="${{ inputs.${var_name} }}"
+          if [ -n "$var_value" ]; then
+            echo "${var_name}=${var_value}"
+            echo "${var_name}=${var_value}" >> $GITHUB_ENV
+          else
+            echo "Error: ${var_name} is not set."
+            exit 1
+          fi
+        done
 
     - uses: actions/checkout@v4
       if: github.event.action != 'closed'
@@ -116,8 +118,12 @@ runs:
 
           # Download values.yml file
           curl -o ./values.yml "${VALUES_URL}"
-          echo "Downloaded values.yml to ./values.yml (current directory: charts/crunchy)"
+          echo "Downloaded values.yml (current directory: charts/crunchy)"
+
+          # Set Helm app name
           sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
+
+          # Package, update and deploy the chart
           helm package -u .
           if [ "$s3_enabled" == "true" ]; then
             helm upgrade --install --wait --set crunchy.pgBackRest.s3.enabled=true \
@@ -134,7 +140,8 @@ runs:
             ${RELEASE_NAME} \
             ./${{ github.event.repository.name }}-5.5.1.tgz
           fi
-          # check if operator deployed the db successfully, retry 10 times with 60 seconds interval
+
+          # Verify successful db deployment; wait retry 10 times with 60 seconds interval
           READY=false
           for i in {1..10}; do
             # Check if the 'db' instance has at least 1 ready replica
