Swap warning for error

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -102,7 +102,8 @@ runs:
           if [ -n "$var_value" ]; then
             echo "${var_name}=${var_value}" >> $GITHUB_ENV
           else
-            echo "Warning: ${var_name} is not set."
+            echo "Error: ${var_name} is not set."
+            exit 1
           fi
         done
 
