chore: simplify params and handling (#6)
Co-authored-by: OMPRAKASH MISHRA <omprakashmishra3978@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -13,10 +13,6 @@ inputs:
   environment:
     description: 'Environment name; omit for PRs'
     required: false
-  s3_enabled:
-    description: 'Enable S3 backups'
-    required: false
-    default: 'false'
   values_file:
     description: 'Path to the values.yml file to use for the deployment'
     required: true
@@ -54,99 +50,104 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Validate Inputs
-      if: inputs.s3_enabled == 'true' && github.event.action != 'closed'
-      shell: bash
+    - shell: bash
       run: |
-        echo "S3 is enabled for backups, checking for mandatory secrets"
-        if [ -z "${{ inputs.s3_access_key }}" ]; then
-          echo "S3 access key not found"
+        # Variables and Inputs
+
+        # Enable S3 backups if all required vars are set
+        s3_vars=("${{ inputs.s3_access_key }}" "${{ inputs.s3_secret_key }}" "${{ inputs.s3_bucket }}" "${{ inputs.s3_endpoint }}")
+        if [ "${#s3_vars[@]}" -eq 4 ]; then
+          echo "All S3 configuration variables are present. Enabling S3 backups."
+          S3_ENABLED=true
+        elif [ "$s3_vars_count" -gt 0 ]; then
+          echo "Warning: Some S3 configuration variables are set, but not all. Please ensure all S3 variables are configured."
           exit 1
-        fi
-        if [ -z "${{ inputs.s3_secret_key }}" ]; then
-          echo "S3 secret key not found"
-          exit 1
-        fi
-        if [ -z "${{ inputs.s3_bucket }}" ]; then
-          echo "S3 bucket not found"
-          exit 1
-        fi
-        if [ -z "${{ inputs.s3_endpoint }}" ]; then
-          echo "S3 endpoint not found"
-          exit 1
+        else
+          echo "S3 configuration not set. Disabling S3 backups."
         fi
 
-    - if: github.event.action != 'closed'
-      uses: actions/checkout@v4
-
-    - name: Release Name
-      id: release_name
-      shell: bash
-      run: |
+        # Release and cluster names; based on a hash of the repository name
         RELEASE_NAME=pg-$(echo -n "${{github.event.repository.name}}" | md5sum | cut -c 1-8)
-        echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_OUTPUT
-        echo "Release name: ${RELEASE_NAME}"
-        echo "CLUSTER_NAME=${RELEASE_NAME}-crunchy" >> $GITHUB_OUTPUT
-        echo "Cluster name: ${RELEASE_NAME}-crunchy"
+        CLUSTER_NAME=${RELEASE_NAME}-crunchy
 
-    - name: Construct values.yml URL
-      id: construct_values_url
-      if: github.event.action != 'closed'
-      shell: bash
-      run: |
-        REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/${{ inputs.values_file }}"
-        echo "values_url=${REPO_URL}" >> $GITHUB_OUTPUT
-        echo "Constructed values.yml URL: ${REPO_URL}"
+        # Construct values.yml URL (ref_name = PR, ref_name = merge, default_branch = default)
+        BRANCH_OR_REF="${{ github.head_ref || github.ref_name || github.event.repository.default_branch }}"
+        VALUES_URL="https://raw.githubusercontent.com/${{ github.repository }}/${BRANCH_OR_REF}/${{ inputs.values_file }}"
 
-    - name: Validate values.yml URL
-      if: github.event.action != 'closed'
-      shell: bash
-      run: |
-        if ! curl --output /dev/null --silent --head --fail "${{ steps.construct_values_url.outputs.values_url }}"; then
-          echo "Error: The constructed values.yml URL is invalid or inaccessible: ${{ steps.construct_values_url.outputs.values_url }}"
+        # Validate values.yml URL
+        if ! curl --output /dev/null --silent --head --fail "${VALUES_URL}"; then
+          echo "Error: The constructed values.yml URL is invalid or inaccessible: ${VALUES_URL}"
           exit 1
         fi
-        echo "Validated values.yml URL: ${{ steps.construct_values_url.outputs.values_url }}"
+        echo "Validated values.yml URL: ${VALUES_URL}"
 
-    - name: Deploy Database
-      uses: bcgov/action-oc-runner@v1.2.1
+        # Process vars and send to GITHUB_ENV
+        declare -A vars=(
+          [s3_access_key]="${{ inputs.s3_access_key }}"
+          [s3_secret_key]="${{ inputs.s3_secret_key }}"
+          [s3_bucket]="${{ inputs.s3_bucket }}"
+          [s3_endpoint]="${{ inputs.s3_endpoint }}"
+          [RELEASE_NAME]="$RELEASE_NAME"
+          [CLUSTER_NAME]="$CLUSTER_NAME"
+          [VALUES_URL]="$VALUES_URL"
+        )
+
+        for var_name in "${!vars[@]}"; do
+          var_value="${vars[$var_name]}"
+          if [ -n "$var_value" ]; then
+            echo "${var_name}=${var_value}"
+            echo "${var_name}=${var_value}" >> $GITHUB_ENV
+          else
+            echo "Error: ${var_name} is not set."
+            exit 1
+          fi
+        done
+
+    - uses: actions/checkout@v4
+      if: github.event.action != 'closed'
+
+    - uses: bcgov/action-oc-runner@v1.2.1
+      id: deploy
       if: github.event.action != 'closed' # avoid running on PR close event, which unnecessarily patches the cluster.
       with:
-        oc_namespace: ${{ inputs.oc_namespace }}
-        oc_token: ${{ inputs.oc_token }}
-        oc_server: ${{ inputs.oc_server }}
+        oc_namespace: "${{ inputs.oc_namespace }}"
+        oc_token: "${{ inputs.oc_token }}"
+        oc_server: "${{ inputs.oc_server }}"
         repository: ${{ github.repository }}
         ref: ${{ inputs.ref }}
-        triggers: ${{ inputs.triggers }}
+        triggers: "${{ inputs.triggers }}"
         commands: |
+          # Deploy Database
           echo 'Deploying crunchy helm chart'
           cd ${{ inputs.directory }}
 
           # Download values.yml file
-          curl -o ./values.yml "${{ steps.construct_values_url.outputs.values_url }}"
-          echo "Downloaded values.yml to ./values.yml (current directory: charts/crunchy)"
+          curl -o ./values.yml "${VALUES_URL}"
+          echo "Downloaded values.yml (current directory: charts/crunchy)"
+
+          # Set Helm app name
           sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
+
+          # Package, update and deploy the chart
           helm package -u .
-          if [ "${{ inputs.s3_enabled }}" == "true" ]; then
+          if [ "$s3_enabled" == "true" ]; then
             helm upgrade --install --wait --set crunchy.pgBackRest.s3.enabled=true \
               --set-string crunchy.pgBackRest.s3.accessKey=${{ inputs.s3_access_key }} \
               --set-string crunchy.pgBackRest.s3.secretKey=${{ inputs.s3_secret_key }} \
               --set-string crunchy.pgBackRest.s3.bucket=${{ inputs.s3_bucket }} \
               --set-string crunchy.pgBackRest.s3.endpoint=${{ inputs.s3_endpoint }} \
-              ${{steps.release_name.outputs.RELEASE_NAME}} \
-              --values ./values.yml \
+              ${RELEASE_NAME} --values ./values.yml \
               ./${{ github.event.repository.name }}-5.5.1.tgz
           else
-            helm upgrade --install --wait \
-            --values ./values.yml \
-            ${{steps.release_name.outputs.RELEASE_NAME}} \
-            ./${{ github.event.repository.name }}-5.5.1.tgz
+            helm upgrade --install --wait ${RELEASE_NAME} --values ./values.yml \
+              ./${{ github.event.repository.name }}-5.5.1.tgz
           fi
-          # check if operator deployed the db successfully, retry 10 times with 60 seconds interval
+
+          # Verify successful db deployment; wait retry 10 times with 60 seconds interval
           READY=false
           for i in {1..10}; do
             # Check if the 'db' instance has at least 1 ready replica
-            if oc get PostgresCluster/${{steps.release_name.outputs.RELEASE_NAME}}-crunchy -o json | jq -e '.status.instances[] | select(.name=="db") | .readyReplicas > 0' > /dev/null 2>&1; then
+            if oc get PostgresCluster/${RELEASE_NAME}-crunchy -o json | jq -e '.status.instances[] | select(.name=="db") | .readyReplicas > 0' > /dev/null 2>&1; then
               echo "Crunchy DB instance 'db' is ready "
               READY=true
               break
@@ -161,72 +162,67 @@ runs:
             exit 1
           fi
 
-    - name: Add PR specific user to Crunchy DB
-      if: github.event_name == 'pull_request' && github.event.action != 'closed'
+    - if: steps.deploy.outputs.triggered == 'true'
+      shell: bash
+      run: |
+        # Add PR specific user to Crunchy DB
+        echo "Adding PR specific user to Crunchy DB"
+        NEW_USER='{"databases":["app-${{ github.event.number }}"],"name":"app-${{ github.event.number }}"}'
+        CURRENT_USERS=$(oc get PostgresCluster/"${CLUSTER_NAME}" -o json | jq '.spec.users')
+        echo "${CURRENT_USERS}"
+
+        # check if current_users already contains the new_user
+        if echo "${CURRENT_USERS}" | jq -e ".[] | select(.name == \"app-${{ github.event.number }}\")" > /dev/null; then
+          echo "User already exists"
+          exit 0
+        fi
+
+        UPDATED_USERS=$(echo "${CURRENT_USERS}" | jq --argjson NEW_USER "${NEW_USER}" '. + [$NEW_USER]')
+        PATCH_JSON=$(jq -n --argjson users "${UPDATED_USERS}" '{"spec": {"users": $users}}')
+        oc patch PostgresCluster/"${CLUSTER_NAME}" --type=merge -p "${PATCH_JSON}"
+        # wait for sometime as it takes time to create the user, query the secret and check if it is created, otherwise wait in a loop for 5 rounds
+        SECRET_FOUND=false
+        for i in {1..5}; do
+          if oc get secret "${CLUSTER_NAME}-pguser-app-${{ github.event.number }}" -o jsonpath='{.metadata.name}' > /dev/null 2>&1; then
+            echo "Secret created"
+            SECRET_FOUND=true
+            break
+          else
+            echo "Attempt $i: Secret not created, waiting for 60 seconds"
+            sleep 60
+          fi
+        done
+
+        if [ "$SECRET_FOUND" = false ]; then
+          echo "Error: Secret ${CLUSTER_NAME}-pguser-app-${{ github.event.number }} was not created after 5 attempts."
+          exit 1
+        fi
+
+    - if: github.event_name == 'pull_request' && github.event.action == 'closed'
       uses: bcgov/action-oc-runner@v1.2.1
       with:
-        oc_namespace: ${{ inputs.oc_namespace }}
-        oc_token: ${{ inputs.oc_token }}
-        oc_server: ${{ inputs.oc_server }}
-        triggers: ${{ inputs.triggers }}
+        oc_namespace: "${{ inputs.oc_namespace }}"
+        oc_token: "${{ inputs.oc_token }}"
+        oc_server: "${{ inputs.oc_server }}"
+        triggers: "${{ inputs.triggers }}"
         commands: |
-          echo 'Adding PR specific user to Crunchy DB'
-          NEW_USER='{"databases":["app-${{ github.event.number }}"],"name":"app-${{ github.event.number }}"}'
-          CURRENT_USERS=$(oc get PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} -o json | jq '.spec.users')
-          echo "${CURRENT_USERS}"
-
-          # check if current_users already contains the new_user
-          if echo "${CURRENT_USERS}" | jq -e ".[] | select(.name == \"app-${{ github.event.number }}\")" > /dev/null; then
-            echo "User already exists"
-            exit 0
-          fi
-
-          UPDATED_USERS=$(echo "${CURRENT_USERS}" | jq --argjson NEW_USER "${NEW_USER}" '. + [$NEW_USER]')
-          PATCH_JSON=$(jq -n --argjson users "${UPDATED_USERS}" '{"spec": {"users": $users}}')
-          oc patch PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} --type=merge -p "${PATCH_JSON}"
-          # wait for sometime as it takes time to create the user, query the secret and check if it is created, otherwise wait in a loop for 5 rounds
-          SECRET_FOUND=false
-          for i in {1..5}; do
-            if oc get secret ${{steps.release_name.outputs.CLUSTER_NAME}}-pguser-app-${{ github.event.number }} -o jsonpath='{.metadata.name}' > /dev/null 2>&1; then
-              echo "Secret created"
-              SECRET_FOUND=true
-              break
-            else
-              echo "Attempt $i: Secret not created, waiting for 60 seconds"
-              sleep 60
-            fi
-          done
-
-          if [ "$SECRET_FOUND" = false ]; then
-            echo "Error: Secret ${{steps.release_name.outputs.CLUSTER_NAME}}-pguser-app-${{ github.event.number }} was not created after 5 attempts."
-            exit 1
-          fi
-
-    - name: Remove PR specific user from Crunchy DB # only for PRs and when PR is closed
-      if: github.event_name == 'pull_request' && github.event.action == 'closed'
-      uses: bcgov/action-oc-runner@v1.2.1
-      with:
-        oc_namespace: ${{ inputs.oc_namespace }}
-        oc_token: ${{ inputs.oc_token }}
-        oc_server: ${{ inputs.oc_server }}
-        triggers: ${{ inputs.triggers }}
-        commands: |
+          # Remove PR specific user from Crunchy DB
           # check if postgres-crunchy exists or else exit
-          oc get PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} || exit 0
+          oc get PostgresCluster/"${CLUSTER_NAME}" || exit 0
           # Remove the user from the crunchy cluster yaml and apply the changes
           USER_TO_REMOVE='{"databases":["app-${{ github.event.number }}"],"name":"app-${{ github.event.number }}"}'
           
           echo 'getting current users from crunchy'
-          CURRENT_USERS=$(oc get PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} -o json | jq '.spec.users')
+          CURRENT_USERS=$(oc get PostgresCluster/"${CLUSTER_NAME}" -o json | jq '.spec.users')
           echo "${CURRENT_USERS}"
           
           # Remove the user from the list, 
           UPDATED_USERS=$(echo "${CURRENT_USERS}" | jq --argjson user "${USER_TO_REMOVE}" 'map(select(. != $user))')
           PATCH_JSON=$(jq -n --argjson users "${UPDATED_USERS}" '{"spec": {"users": $users}}')
-          oc patch PostgresCluster/${{steps.release_name.outputs.CLUSTER_NAME}} --type=merge -p "${PATCH_JSON}"
+          oc patch PostgresCluster/"${CLUSTER_NAME}" --type=merge -p "${PATCH_JSON}"
           
           # get primary crunchy pod and remove the role and db
-          CRUNCHY_PG_PRIMARY_POD_NAME=$(oc get pods -l postgres-operator.crunchydata.com/cluster=${{steps.release_name.outputs.CLUSTER_NAME}},postgres-operator.crunchydata.com/role=master -o json | jq -r '.items[0].metadata.name')
+          CRUNCHY_PG_PRIMARY_POD_NAME=$(oc get pods -l postgres-operator.crunchydata.com/cluster="${CLUSTER_NAME}",postgres-operator.crunchydata.com/role=master -o json | jq -r '.items[0].metadata.name')
           
           echo "${CRUNCHY_PG_PRIMARY_POD_NAME}"
           # Terminate all connections to the database before trying terminate and Drop the databse and role right after
