Verify action outputs

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -34,6 +34,14 @@ jobs:
           s3_endpoint: ${{ secrets.s3_endpoint }}
           force_cleanup: true
 
+      - run: |
+          # Verify outputs
+          echo "Outputs: ${{ toJSON(steps.deploy_db.outputs) }}"
+          if [ "${{ steps.deploy_db.outputs.cluster }}" == "" ]||[ "${{ steps.deploy_db.outputs.release }}" == "" ]]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
+
   results:
     name: Results
     needs: [deploy-db]
